
CloseS1 = [];
CloseS2 = [];
CloseS3 = [];
CloseS4 = [];
CloseS5 = [];
CloseS6 = [];
CloseS7 = [];
CloseS8 = [];
CloseS9 = [];
CloseS0 = [];

ticker1 = 'GOOG';
ticker2 = 'FB';
ticker3 = 'AMZN';
ticker4 = 'AAPL';
ticker5 = 'UBER';
ticker6 = 'NVDA';
ticker7 = 'DXCM';
ticker8 = 'BAC';
ticker9 = 'BA';
ticker0 = 'KO';

btcode1 = "data1 = IBMatlab('action', 'query', 'Symbol', ticker1);close1 = data1.askPrice; CloseS1 = [CloseS1, close1];CloseS1(CloseS1==-1)=[]";
btcode2 = "data2 = IBMatlab('action', 'query', 'Symbol', ticker2);close2 = data2.askPrice; CloseS2 = [CloseS2, close2];CloseS2(CloseS2==-1)=[]";
btcode3 = "data3 = IBMatlab('action', 'query', 'Symbol', ticker3);close3 = data3.askPrice; CloseS3 = [CloseS3, close3];CloseS3(CloseS3==-1)=[]";
btcode4 = "data4 = IBMatlab('action', 'query', 'Symbol', ticker4);close4 = data4.askPrice; CloseS4 = [CloseS4, close4];CloseS4(CloseS4==-1)=[]";
btcode5 = "data5 = IBMatlab('action', 'query', 'Symbol', ticker5);close5 = data5.askPrice; CloseS5 = [CloseS5, close5];CloseS5(CloseS5==-1)=[]";
btcode6 = "data6 = IBMatlab('action', 'query', 'Symbol', ticker6);close6 = data6.askPrice; CloseS6 = [CloseS6, close6];CloseS6(CloseS6==-1)=[]";
btcode7 = "data7 = IBMatlab('action', 'query', 'Symbol', ticker7);close7 = data7.askPrice; CloseS7 = [CloseS7, close7];CloseS7(CloseS7==-1)=[]";
btcode8 = "data8 = IBMatlab('action', 'query', 'Symbol', ticker8);close8 = data8.askPrice; CloseS8 = [CloseS8, close8];CloseS8(CloseS8==-1)=[]";
btcode9 = "data9 = IBMatlab('action', 'query', 'Symbol', ticker9);close9 = data9.askPrice; CloseS9 = [CloseS9, close9];CloseS9(CloseS9==-1)=[]";
btcode0 = "data0 = IBMatlab('action', 'query', 'Symbol', ticker0);close0 = data0.askPrice; CloseS0 = [CloseS0, close0];CloseS0(CloseS0==-1)=[]";

timer_bt1 = timer('timerFcn', btcode1,'ExecutionMode', 'fixedRate', 'Period', 5);
timer_bt2 = timer('timerFcn', btcode2,'ExecutionMode', 'fixedRate', 'Period', 5);
timer_bt3 = timer('timerFcn', btcode3,'ExecutionMode', 'fixedRate', 'Period', 5);
timer_bt4 = timer('timerFcn', btcode4,'ExecutionMode', 'fixedRate', 'Period', 5);
timer_bt5 = timer('timerFcn', btcode5,'ExecutionMode', 'fixedRate', 'Period', 5);
timer_bt6 = timer('timerFcn', btcode6,'ExecutionMode', 'fixedRate', 'Period', 5);
timer_bt7 = timer('timerFcn', btcode7,'ExecutionMode', 'fixedRate', 'Period', 5);
timer_bt8 = timer('timerFcn', btcode8,'ExecutionMode', 'fixedRate', 'Period', 5);
timer_bt9 = timer('timerFcn', btcode9,'ExecutionMode', 'fixedRate', 'Period', 5);
timer_bt0 = timer('timerFcn', btcode0,'ExecutionMode', 'fixedRate', 'Period', 5);

start(timer_bt1);
start(timer_bt2);
start(timer_bt3);
start(timer_bt4);
start(timer_bt5);
start(timer_bt6);
start(timer_bt7);
start(timer_bt8);
start(timer_bt9);
start(timer_bt0);

pause(240)

stop(timer_bt1);
stop(timer_bt2);
stop(timer_bt3);
stop(timer_bt4);
stop(timer_bt5);
stop(timer_bt6);
stop(timer_bt7);
stop(timer_bt8);
stop(timer_bt9);
stop(timer_bt0);

% PortVal_init = (close1+close2+close3+close4+close5+close6+close7+close8+close9+close0)/10;
% display(['Initial Portforlio Value: ', num2str(PortVal_init)])
% PortVals = [PortVal_init];

table1 = table(transpose(CloseS1));
table1.Properties.VariableNames={'Close'};

table2 = table(transpose(CloseS2));
table2.Properties.VariableNames={'Close'};

table3 = table(transpose(CloseS3));
table3.Properties.VariableNames={'Close'};

table5 = table(transpose(CloseS5));
table5.Properties.VariableNames={'Close'};

table4 = table(transpose(CloseS4));
table4.Properties.VariableNames={'Close'};

table6 = table(transpose(CloseS6));
table6.Properties.VariableNames={'Close'};

table7 = table(transpose(CloseS7));
table7.Properties.VariableNames={'Close'};

table8 = table(transpose(CloseS8));
table8.Properties.VariableNames={'Close'};

table9 = table(transpose(CloseS9));
table9.Properties.VariableNames={'Close'};

table0 = table(transpose(CloseS0));
table0.Properties.VariableNames={'Close'};


[Signals1, CumReturns1, FinalCumReturn1, FinalCumReturn_nosignal1] = fproj_backtest(table1);
[Signals2, CumReturns2, FinalCumReturn2, FinalCumReturn_nosignal2] = fproj_backtest(table2);
[Signals3, CumReturns3, FinalCumReturn3, FinalCumReturn_nosignal3] = fproj_backtest(table3);
[Signals4, CumReturns4, FinalCumReturn4, FinalCumReturn_nosignal4] = fproj_backtest(table4);
[Signals5, CumReturns5, FinalCumReturn5, FinalCumReturn_nosignal5] = fproj_backtest(table5);
[Signals6, CumReturns6, FinalCumReturn6, FinalCumReturn_nosignal6] = fproj_backtest(table6);
[Signals7, CumReturns7, FinalCumReturn7, FinalCumReturn_nosignal7] = fproj_backtest(table7);
[Signals8, CumReturns8, FinalCumReturn8, FinalCumReturn_nosignal8] = fproj_backtest(table8);
[Signals9, CumReturns9, FinalCumReturn9, FinalCumReturn_nosignal9] = fproj_backtest(table9);
[Signals0, CumReturns0, FinalCumReturn0, FinalCumReturn_nosignal0] = fproj_backtest(table0);

position1 = [Signals1(end)];
position2 = [Signals2(end)];
position3 = [Signals3(end)];
position4 = [Signals4(end)];
position5 = [Signals5(end)];
position6 = [Signals6(end)];
position7 = [Signals7(end)];
position8 = [Signals8(end)];
position9 = [Signals9(end)];
position0 = [Signals0(end)];

cells = {'', ''};
cells = transpose(cells);

event_table = cell2table(cells)
event_table.Properties.VariableNames={'Event'}

sigs = [Signals1(end), Signals2(end), Signals3(end), Signals4(end), Signals5(end), Signals6(end), Signals7(end), Signals8(end), Signals9(end), Signals0(end)];
tics = {ticker1, ticker2, ticker3, ticker4, ticker5, ticker6, ticker7, ticker8, ticker9, ticker0};

for k = 1:length(sigs)
    ti = tics{k};
    if k == 1
        orderid = IBMatlab('action','BUY','symbol',ti,'quantity',1,'type','MKT');
        display([ti, ': initial position 1; Buy order released ', num2str(orderid)])
    elseif k == -1
        orderid = IBMatlab('action','SELL','symbol',ti,'quantity',1,'type','MKT');
        display([ti, ': initial position -1; Sell order released ', num2str(orderid)])
    else
        disp([ti, ': initial position 0'])
    end
end

code1 = ["i1 = i1+1;"...
"data1 = IBMatlab('action', 'query', 'Symbol', ticker1);"...
"close1 = data1.askPrice;"...
"if close1 ==-1;"...
"close1 = table1.Close(end);"...
"end;"...
"table1.Close(end+1) = close1;"...
"table1 = table1(2:end,:);"...
"signal1 = fproj_signal(table1);"...
"display([ticker1, ' #', num2str(i1), ': ', 'price ', num2str(close1), '; signal ',num2str(signal1)]);"...
"if signal1>0 && position1(end) <1;"...
"order1 = IBMatlab('action','BUY','symbol',ticker1,'quantity',signal1,'type','MKT');"...
"position1 = [position1, position1(end)+signal1];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker1, ' Buy orderID #', num2str(order1), ' current position ', num2str(position1(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker1, ' Buy orderID #', num2str(order1), ' current position ', num2str(position1(end))]};"...
"elseif signal1<0 && position1(end) >-1;"...
"order1 = IBMatlab('action','SELL','symbol',ticker1,'quantity',-signal1,'type','MKT');"...
"position1 = [position1, position1(end)+signal1];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker1, ' Sell orderID #', num2str(order1), ' current position ', num2str(position1(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker1, ' Sell orderID #', num2str(order1), ' current position ', num2str(position1(end))]};"...
"else;"...
"position1 = [position1, position1(end)];"...
"end;"];

code2 = ["i2 = i2+1;"...
"data2 = IBMatlab('action', 'query', 'Symbol', ticker2);"...
"close2 = data2.askPrice;"...
"if close2 ==-1;"...
"close2 = table2.Close(end);"...
"end;"...
"table2.Close(end+1) = close2;"...
"table2 = table2(2:end,:);"...
"signal2 = fproj_signal(table2);"...
"display([ticker2, ' #', num2str(i2), ': ', 'price ', num2str(close2), '; signal ',num2str(signal2)]);"...
"if signal2>0 && position2(end) <1;"...
"order2 = IBMatlab('action','BUY','symbol',ticker2,'quantity',signal2,'type','MKT');"...
"position2 = [position2, position2(end)+signal2];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker2, ' Buy orderID #', num2str(order2), ' current position ', num2str(position2(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker2, ' Buy orderID #', num2str(order2), ' current position ', num2str(position2(end))]};"...
"elseif signal2<0 && position2(end) >-1;"...
"order2 = IBMatlab('action','SELL','symbol',ticker2,'quantity',-signal2,'type','MKT');"...
"position2 = [position2, position2(end)+signal2];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker2, ' Sell orderID #', num2str(order2), ' current position ', num2str(position2(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker2, ' Sell orderID #', num2str(order2), ' current position ', num2str(position2(end))]};"...
"else;"...
"position2 = [position2, position2(end)];"...
"end;"];

code3 = ["i3 = i3+1;"...
"data3 = IBMatlab('action', 'query', 'Symbol', ticker3);"...
"close3 = data3.askPrice;"...
"if close3 ==-1;"...
"close3 = table3.Close(end);"...
"end;"...
"table3.Close(end+1) = close3;"...
"table3 = table3(2:end,:);"...
"signal3 = fproj_signal(table3);"...
"display([ticker3, ' #', num2str(i3), ': ', 'price ', num2str(close3), '; signal ',num2str(signal3)]);"...
"if signal3>0 && position3(end) <1;"...
"order3 = IBMatlab('action','BUY','symbol',ticker3,'quantity',signal3,'type','MKT');"...
"position3 = [position3, position3(end)+signal3];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker3, ' Buy orderID #', num2str(order3), ' current position ', num2str(position3(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker3, ' Buy orderID #', num2str(order3), ' current position ', num2str(position3(end))]};"...
"elseif signal3<0 && position3(end) >-1;"...
"order3 = IBMatlab('action','SELL','symbol',ticker3,'quantity',-signal3,'type','MKT');"...
"position3 = [position3, position3(end)+signal3];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker3, ' Sell orderID #', num2str(order3), ' current position ', num2str(position3(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker3, ' Sell orderID #', num2str(order3), ' current position ', num2str(position3(end))]};"...
"else;"...
"position3 = [position3, position3(end)];"...
"end;"];

code4 = ["i4 = i4+1;"...
"data4 = IBMatlab('action', 'query', 'Symbol', ticker4);"...
"close4 = data4.askPrice;"...
"if close4 ==-1;"...
"close4 = table4.Close(end);"...
"end;"...
"table4.Close(end+1) = close4;"...
"table4 = table4(2:end,:);"...
"signal4 = fproj_signal(table4);"...
"display([ticker4, ' #', num2str(i4), ': ', 'price ', num2str(close4), '; signal ',num2str(signal4)]);"...
"if signal4>0 && position4(end) <1;"...
"order4 = IBMatlab('action','BUY','symbol',ticker4,'quantity',signal4,'type','MKT');"...
"position4 = [position4, position4(end)+signal4];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker4, ' Buy orderID #', num2str(order4), ' current position ', num2str(position4(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker4, ' Buy orderID #', num2str(order4), ' current position ', num2str(position4(end))]};"...
"elseif signal4<0 && position4(end) >-1;"...
"order4 = IBMatlab('action','SELL','symbol',ticker4,'quantity',-signal4,'type','MKT');"...
"position4 = [position4, position4(end)+signal4];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker4, ' Sell orderID #', num2str(order4), ' current position ', num2str(position4(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker4, ' Sell orderID #', num2str(order4), ' current position ', num2str(position4(end))]};"...
"else;"...
"position4 = [position4, position4(end)];"...
"end;"];

code5 = ["i5 = i5+1;"...
"data5 = IBMatlab('action', 'query', 'Symbol', ticker5);"...
"close5 = data5.askPrice;"...
"if close5 ==-1;"...
"close5 = table5.Close(end);"...
"end;"...
"table5.Close(end+1) = close5;"...
"table5 = table5(2:end,:);"...
"signal5 = fproj_signal(table5);"...
"display([ticker5, ' #', num2str(i5), ': ', 'price ', num2str(close5), '; signal ',num2str(signal5)]);"...
"if signal5>0 && position5(end) <1;"...
"order5 = IBMatlab('action','BUY','symbol',ticker5,'quantity',signal5,'type','MKT');"...
"position5 = [position5, position5(end)+signal5];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker5, ' Buy orderID #', num2str(order5), ' current position ', num2str(position5(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker5, ' Buy orderID #', num2str(order5), ' current position ', num2str(position5(end))]};"...
"elseif signal5<0 && position5(end) >-1;"...
"order5 = IBMatlab('action','SELL','symbol',ticker5,'quantity',-signal5,'type','MKT');"...
"position5 = [position5, position5(end)+signal5];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker5, ' Sell orderID #', num2str(order5), ' current position ', num2str(position5(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker5, ' Sell orderID #', num2str(order5), ' current position ', num2str(position5(end))]};"...
"else;"...
"position5 = [position5, position5(end)];"...
"end;"];

code6 = ["i6 = i6+1;"...
"data6 = IBMatlab('action', 'query', 'Symbol', ticker6);"...
"close6 = data6.askPrice;"...
"if close6 ==-1;"...
"close6 = table6.Close(end);"...
"end;"...
"table6.Close(end+1) = close6;"...
"table6 = table6(2:end,:);"...
"signal6 = fproj_signal(table6);"...
"display([ticker6, ' #', num2str(i6), ': ', 'price ', num2str(close6), '; signal ',num2str(signal6)]);"...
"if signal6>0 && position6(end) <1;"...
"order6 = IBMatlab('action','BUY','symbol',ticker6,'quantity',signal6,'type','MKT');"...
"position6 = [position6, position6(end)+signal6];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker6, ' Buy orderID #', num2str(order6), ' current position ', num2str(position6(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker6, ' Buy orderID #', num2str(order6), ' current position ', num2str(position6(end))]};"...
"elseif signal6<0 && position6(end) >-1;"...
"order6 = IBMatlab('action','SELL','symbol',ticker6,'quantity',-signal6,'type','MKT');"...
"position6 = [position6, position6(end)+signal6];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker6, ' Sell orderID #', num2str(order6), ' current position ', num2str(position6(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker6, ' Sell orderID #', num2str(order6), ' current position ', num2str(position6(end))]};"...
"else;"...
"position6 = [position6, position6(end)];"...
"end;"];

code7 = ["i7 = i7+1;"...
"data7 = IBMatlab('action', 'query', 'Symbol', ticker7);"...
"close7 = data7.askPrice;"...
"if close7 ==-1;"...
"close7 = table7.Close(end);"...
"end;"...
"table7.Close(end+1) = close7;"...
"table7 = table7(2:end,:);"...
"signal7 = fproj_signal(table7);"...
"display([ticker7, ' #', num2str(i7), ': ', 'price ', num2str(close7), '; signal ',num2str(signal7)]);"...
"if signal7>0 && position7(end) <1;"...
"order7 = IBMatlab('action','BUY','symbol',ticker7,'quantity',signal7,'type','MKT');"...
"position7 = [position7, position7(end)+signal7];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker7, ' Buy orderID #', num2str(order7), ' current position ', num2str(position7(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker7, ' Buy orderID #', num2str(order7), ' current position ', num2str(position7(end))]};"...
"elseif signal7<0 && position7(end) >-1;"...
"order7 = IBMatlab('action','SELL','symbol',ticker7,'quantity',-signal7,'type','MKT');"...
"position7 = [position7, position7(end)+signal7];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker7, ' Sell orderID #', num2str(order7), ' current position ', num2str(position7(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker7, ' Sell orderID #', num2str(order7), ' current position ', num2str(position7(end))]};"...
"else;"...
"position7 = [position7, position7(end)];"...
"end;"];

code8 = ["i8 = i8+1;"...
"data8 = IBMatlab('action', 'query', 'Symbol', ticker8);"...
"close8 = data8.askPrice;"...
"if close8 ==-1;"...
"close8 = table8.Close(end);"...
"end;"...
"table8.Close(end+1) = close8;"...
"table8 = table8(2:end,:);"...
"signal8 = fproj_signal(table8);"...
"display([ticker8, ' #', num2str(i8), ': ', 'price ', num2str(close8), '; signal ',num2str(signal8)]);"...
"if signal8>0 && position8(end) <1;"...
"order8 = IBMatlab('action','BUY','symbol',ticker8,'quantity',signal8,'type','MKT');"...
"position8 = [position8, position8(end)+signal8];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker8, ' Buy orderID #', num2str(order8), ' current position ', num2str(position8(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker8, ' Buy orderID #', num2str(order8), ' current position ', num2str(position8(end))]};"...
"elseif signal8<0 && position8(end) >-1;"...
"order8 = IBMatlab('action','SELL','symbol',ticker8,'quantity',-signal8,'type','MKT');"...
"position8 = [position8, position8(end)+signal8];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker8, ' Sell orderID #', num2str(order8), ' current position ', num2str(position8(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker8, ' Sell orderID #', num2str(order8), ' current position ', num2str(position8(end))]};"...
"else;"...
"position8 = [position8, position8(end)];"...
"end;"];

code9 = ["i9 = i9+1;"...
"data9 = IBMatlab('action', 'query', 'Symbol', ticker9);"...
"close9 = data9.askPrice;"...
"if close9 ==-1;"...
"close9 = table9.Close(end);"...
"end;"...
"table9.Close(end+1) = close9;"...
"table9 = table9(2:end,:);"...
"signal9 = fproj_signal(table9);"...
"display([ticker9, ' #', num2str(i9), ': ', 'price ', num2str(close9), '; signal ',num2str(signal9)]);"...
"if signal9>0 && position9(end) <1;"...
"order9 = IBMatlab('action','BUY','symbol',ticker9,'quantity',signal9,'type','MKT');"...
"position9 = [position9, position9(end)+signal9];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker9, ' Buy orderID #', num2str(order9), ' current position ', num2str(position9(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker9, ' Buy orderID #', num2str(order9), ' current position ', num2str(position9(end))]};"...
"elseif signal9<0 && position9(end) >-1;"...
"order9 = IBMatlab('action','SELL','symbol',ticker9,'quantity',-signal9,'type','MKT');"...
"position9 = [position9, position9(end)+signal9];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker9, ' Sell orderID #', num2str(order9), ' current position ', num2str(position9(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker9, ' Sell orderID #', num2str(order9), ' current position ', num2str(position9(end))]};"...
"else;"...
"position9 = [position9, position9(end)];"...
"end;"];

code0 = ["i0 = i0+1;"...
"data0 = IBMatlab('action', 'query', 'Symbol', ticker0);"...
"close0 = data0.askPrice;"...
"if close0 ==-1;"...
"close0 = table0.Close(end);"...
"end;"...
"table0.Close(end+1) = close0;"...
"table0 = table0(2:end,:);"...
"signal0 = fproj_signal(table0);"...
"display([ticker0, ' #', num2str(i0), ': ', 'price ', num2str(close0), '; signal ',num2str(signal0)]);"...
"if signal0>0 && position0(end) <1;"...
"order0 = IBMatlab('action','BUY','symbol',ticker0,'quantity',signal0,'type','MKT');"...
"position0 = [position0, position0(end)+signal0];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker0, ' Buy orderID #', num2str(order0), ' current position ', num2str(position0(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker0, ' Buy orderID #', num2str(order0), ' current position ', num2str(position0(end))]};"...
"elseif signal0<0 && position0(end) >-1;"...
"order0 = IBMatlab('action','SELL','symbol',ticker0,'quantity',-signal0,'type','MKT');"...
"position0 = [position0, position0(end)+signal0];"...
"display([datestr(now, 'HH:MM:SS'), ' ',ticker0, ' Sell orderID #', num2str(order0), ' current position ', num2str(position0(end))]);"...
"event_table.Event(end+1) = {[datestr(now, 'HH:MM:SS'), ' ',ticker0, ' Sell orderID #', num2str(order0), ' current position ', num2str(position0(end))]};"...
"else;"...
"position0 = [position0, position0(end)];"...
"end;"];

code_ret = ["PortVal_current = (close1+close2+close3+close4+close5)/5;"...
    "current_return = (PortVal_current - PortVal_init)/PortVal_init;"...
    "PortVals = [PortVals, PortVal_current];"...
    "display(['Current Return: ', num2str(current_return)]);"...
    "fprintf('\n');"];

timer_lt1 = timer('timerFcn', concatstring(code1),'ExecutionMode', 'fixedRate', 'Period', 5);
timer_lt2 = timer('timerFcn', concatstring(code2),'ExecutionMode', 'fixedRate', 'Period', 5);
timer_lt3 = timer('timerFcn', concatstring(code3),'ExecutionMode', 'fixedRate', 'Period', 5);
timer_lt4 = timer('timerFcn', concatstring(code4),'ExecutionMode', 'fixedRate', 'Period', 5);
timer_lt5 = timer('timerFcn', concatstring(code5),'ExecutionMode', 'fixedRate', 'Period', 5);
timer_lt6 = timer('timerFcn', concatstring(code6),'ExecutionMode', 'fixedRate', 'Period', 5);
timer_lt7 = timer('timerFcn', concatstring(code7),'ExecutionMode', 'fixedRate', 'Period', 5);
timer_lt8 = timer('timerFcn', concatstring(code8),'ExecutionMode', 'fixedRate', 'Period', 5);
timer_lt9 = timer('timerFcn', concatstring(code9),'ExecutionMode', 'fixedRate', 'Period', 5);
timer_lt0 = timer('timerFcn', concatstring(code0),'ExecutionMode', 'fixedRate', 'Period', 5);
timer_ret = timer('timerFcn', concatstring(code_ret),'ExecutionMode', 'fixedRate', 'Period', 5);

i1 = 0;
i2 = 0;
i3 = 0;
i4 = 0;
i5 = 0;
i6 = 0;
i7 = 0;
i8 = 0;
i9 = 0;
i0 = 0;

start(timer_lt1);
start(timer_lt2);
start(timer_lt3);
start(timer_lt4);
start(timer_lt5);
start(timer_lt6);
start(timer_lt7);
start(timer_lt8);
start(timer_lt9);
start(timer_lt0);
pause(1)

start(timer_ret);
table=event_table
